### ISSUE TITLE
Cant Make Http-Getter

### ISSUE THREAD

**Issue by rayhammerco** [tohojo/http-getter#4]
When installing http-getter it does not see cURL and does not show where it is looking for it:
lab@lab-Macmini:/home/http-getter$ sudo make 
mkdir -p build
cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:28 (MESSAGE):
  Could not find cURL on your system

-- Configuring incomplete, errors occurred!
See also "/home/http-getter/build/CMakeFiles/CMakeOutput.log".
Makefile:8: recipe for target 'build/Makefile' failed
make: *** [build/Makefile] Error 1
lab@lab-Macmini:/home/http-getter$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

lab@lab-Macmini:/home/http-getter$ sudo make 
mkdir -p build
cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:28 (MESSAGE):
  Could not find cURL on your system

-- Configuring incomplete, errors occurred!
See also "/home/http-getter/build/CMakeFiles/CMakeOutput.log".
Makefile:8: recipe for target 'build/Makefile' failed
make: *** [build/Makefile] Error 1

lab@lab-Macmini:/home/http-getter$ which curl
/usr/bin/curl

ab@lab-Macmini:/home/http-getter$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
lab@lab-Macmini:/home/http-getter$ 

Thank you

**Comment by tohojo** [comment]
Do you have the development libraries for cURL installed (-dev package
suffix on Debian)?

**Comment by rayhammerco** [comment]
Looks like that was it.

Im still seeing an error for 14:36:54 INFO: Starting http test. Expected run time: 5 seconds.
14:36:54 ERROR: Runner HTTP latency failed check: No http-getter binary found in PATH.

Though

lab@lab-Macmini:/home/http-getter$ ls
build  CMakeLists.txt  include  LICENSE  Makefile  packaging  README.md  src
lab@lab-Macmini:/home/http-getter$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/http-getter
lab@lab-Macmini:/home/http-getter$

**Comment by tohojo** [comment]
rayhammerco <notifications@github.com> writes:

> Looks like that was it.
>
> Im still seeing an error for 14:36:54 INFO: Starting http test. Expected run time: 5 seconds.
> 14:36:54 ERROR: Runner HTTP latency failed check: No http-getter binary found in PATH.
>
> Though
>
> lab@lab-Macmini:/home/http-getter$ ls
> build  CMakeLists.txt  include  LICENSE  Makefile  packaging  README.md  src
> lab@lab-Macmini:/home/http-getter$ echo $PATH
> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/http-getter

The binary will end up in the build/ subdirectory, so either add that to
your PATH, or move the binary into one of the directories you already
added.

A 'sudo make install' should stick the binary in /usr/local/bin

**Comment by rayhammerco** [comment]
thanks again!
